"""Re-render the slides and compose the final video.

Reuses the narration already generated by build.py. Two fixes over the first pass:

* Colour was keyed on the substring "failed", so `failed=0` -- the *good* outcome -- rendered red,
  and a whole wrapped paragraph inherited the colour of its first line.
* The mp4 concat demuxer doubled the runtime (279s of clips became 559s). Composing from an image
  sequence against one continuous audio track avoids intermediate mp4s entirely.
"""
from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

import build as B

OUT = B.OUT


def colour_for(line: str) -> tuple[int, int, int]:
    l = line.lower().strip()
    if not l:
        return B.FG
    if l.startswith("$") or l.startswith("git clone") or l.startswith("uv "):
        return B.ACCENT
    if "[defect" in l or "reject" in l:
        return B.BAD
    if "[  ok" in l or "accept" in l:
        return B.GOOD
    if "verdict" in l or "[skipped" in l or "revise" in l or "indeterminate" in l:
        return B.WARN
    # exit=1 / failed=N (N>0) is the red signal; failed=0 is not.
    if re.search(r"failed=(?!0\b)\d+", l) or "exit=1" in l:
        return B.BAD
    if re.search(r"passed=(?!0\b)\d+", l) or "exit=0" in l or " passed" in l:
        return B.GOOD
    return B.FG


def wrap(raw: str, width: int = 104) -> list[str]:
    if len(raw) <= width:
        return [raw]
    indent = " " * (len(raw) - len(raw.lstrip()) + 4)
    words, out, cur = raw.split(), [], ""
    for w in words:
        candidate = f"{cur} {w}".strip()
        if len(candidate) > width and cur:
            out.append(cur)
            cur = indent + w
        else:
            cur = candidate
    if cur:
        out.append(cur)
    return out


def slide(path: Path, title: str, lines: list[str], footer: str = "") -> None:
    img = Image.new("RGB", (B.W, B.H), B.BG)
    d = ImageDraw.Draw(img)
    d.text((90, 62), title, font=B.F_TITLE, fill=B.ACCENT)
    d.line([(90, 132), (B.W - 90, 132)], fill=(48, 54, 61), width=2)

    y = 190
    for raw in lines:
        fill = colour_for(raw)
        for line in wrap(raw):
            d.text((90, y), line, font=B.F_BODY, fill=fill)
            y += B.F_BODY.size + 14
            if y > B.H - 130:
                break
        if y > B.H - 130:
            break

    if footer:
        d.text((90, B.H - 78), footer, font=B.F_SMALL, fill=B.DIM)
    img.save(path)


def duration(path: Path) -> float:
    probe = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "json", str(path)],
        capture_output=True, text=True, check=True,
    )
    return float(json.loads(probe.stdout)["format"]["duration"])


def main() -> None:
    frames: list[tuple[Path, float]] = []
    audios: list[Path] = []

    for i, (_text, title, lines, _hero, footer) in enumerate(B.SEGMENTS):
        png, m4a = OUT / f"s{i:02d}.png", OUT / f"s{i:02d}.m4a"
        slide(png, title, lines, footer)
        dur = duration(m4a)
        frames.append((png, dur))
        audios.append(m4a)
        print(f"  {i:02d} {dur:5.1f}s  {title[:60]}")

    landing = OUT / "s99.png"
    slide(landing, B.LANDING[0], B.LANDING[1], B.LANDING[2])
    frames.append((landing, 6.0))

    total = sum(d for _, d in frames)
    print(f"\ntotal {total:.1f}s = {int(total // 60)}:{int(total % 60):02d}")

    # One continuous audio track: every narration segment, then silence under the landing card.
    silence = OUT / "silence.m4a"
    subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-f", "lavfi", "-i",
         "anullsrc=r=44100:cl=stereo", "-t", "6", "-c:a", "aac", str(silence)], check=True,
    )
    # Decode to PCM and join in the filter graph. Stream-copying 13 AAC files appends each one's
    # encoder priming padding, which added 16 seconds of silence in total and walked the slides
    # out of sync with the voice reading them.
    voice = OUT / "voice.wav"
    inputs: list[str] = []
    for p in audios + [silence]:
        inputs += ["-i", str(p)]
    n = len(audios) + 1
    subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", *inputs,
         "-filter_complex", "".join(f"[{i}:a]" for i in range(n)) + f"concat=n={n}:v=0:a=1[out]",
         "-map", "[out]", "-c:a", "pcm_s16le", str(voice)], check=True,
    )
    print(f"  voice track {duration(voice):.1f}s against {total:.1f}s of slides")

    # Image sequence with explicit per-frame durations. The concat demuxer requires the final
    # entry to be repeated without a duration, or it drops the last frame.
    ilist = OUT / "images.txt"
    body = "".join(f"file '{p}'\nduration {d:.3f}\n" for p, d in frames)
    ilist.write_text(body + f"file '{frames[-1][0]}'\n")

    final = B.HERE / "rewardgate-demo.mp4"
    subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error",
         "-f", "concat", "-safe", "0", "-i", str(ilist),
         "-i", str(voice),
         "-c:v", "libx264", "-preset", "medium", "-crf", "20", "-pix_fmt", "yuv420p",
         "-r", "25", "-fps_mode", "cfr",
         "-c:a", "aac", "-b:a", "160k", "-shortest", "-movflags", "+faststart", str(final)],
        check=True,
    )
    print(f"wrote {final}  ({duration(final):.1f}s)")


if __name__ == "__main__":
    main()
